#pragma once

#if defined(_MSC_BUILD)

#define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING 1
#define _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS 1
#define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE 1

#endif
